modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "terrarium"
version = "${version}"
displayName = "terrarium"
authors = ""
description = '''
'''
#logoFile = ""

[[dependencies.terrarium]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.terrarium]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.terrarium]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "SERVER"

[[mixins]]
config = "terrarium.mixins.json"
